### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by haithanhp** [juhongm999/chm#1]
Hi @juhongm999 ,

Thanks for your great work. I want to reproduce your results and visualization. How can we draw images of correspondence between 2 images? (e.g. cat images in Figure 1 of your paper). Do you have any implementation for that? Thanks!!

Best,
Hai

**Comment by juhongm999** [comment]
We used below code to visualize predictions

`

    
    from PIL import Image, ImageDraw
    import numpy as np
    import torchvision.transforms as transforms
    import torch.nn.functional as F
    import torch
    import cv2class Visualizer:

    @classmethod
    def initialize(cls):
        cls.colors = [(255, 102, 102),
                      (255, 179, 102),
                      (255, 255, 102),
                      (179, 255, 102),
                      (102, 255, 217),
                      (102, 217, 255),
                      (102, 140, 255),
                      (140, 102, 255),
                      (255, 102, 255),
                      (255, 255, 255),
                      (0, 0, 0)]
        cls.unnorm = UnNormalize()
        cls.to_pil = transforms.ToPILImage()

    @classmethod
    def merge_image_pair(cls, src_img, trg_img):
        r""" Horizontally aligns a pair of pytorch tensor images (3, H, W) and returns PIL object """
        if str(type(src_img)) == "<class 'torch.Tensor'>":
            src_pil = cls.to_pil(cls.unnorm(src_img.cpu()))
            trg_pil = cls.to_pil(cls.unnorm(trg_img.cpu()))
        else:
            src_pil = src_img
            trg_pil = trg_img

        canvas_width = src_pil.size[0] + trg_pil.size[0]
        canvas_height = max(src_pil.size[1], trg_pil.size[1])
        canvas = Image.new('RGB', (canvas_width, canvas_height))

        canvas.paste(src_pil, (0, 0))
        canvas.paste(trg_pil, (src_pil.size[0], 0))

        return canvas

    @classmethod
    def visualize_prediction(cls, src_img, trg_img, src_kps, trg_kps, prd_kps, path, radius=3, alpha=0.1):
        r""" Visualizes keypoint predictions (N, 2) on a pair of pytorch tensor images (3, H, W) """
        pair_img = cls.merge_image_pair(src_img, trg_img)
        draw = ImageDraw.Draw(pair_img)

        trg_kps[:, 0] = trg_kps[:, 0] + trg_img.size(2)
        prd_kps[:, 0] = prd_kps[:, 0] + trg_img.size(2)
        src_kps = src_kps.cpu()
        trg_kps = trg_kps.cpu()
        prd_kps = prd_kps.cpu()

        for src_kp, trg_kp, prd_kp in zip(src_kps, trg_kps, prd_kps):
            correct = (trg_kp - prd_kp).pow(2).sum().pow(0.5) <= (240 * alpha)

            color = 'green' if correct else 'red'
            draw.ellipse((src_kp[0] - radius, src_kp[1] - radius, src_kp[0] + radius, src_kp[1] + radius), fill=color, outline=1)
            draw.ellipse((trg_kp[0] - radius, trg_kp[1] - radius, trg_kp[0] + radius, trg_kp[1] + radius), fill=color, outline=1)

            draw.line((prd_kp[0] - radius, prd_kp[1] - radius, prd_kp[0] + radius, prd_kp[1] + radius), fill=color, width=2)
            draw.line((prd_kp[0] + radius, prd_kp[1] - radius, prd_kp[0] - radius, prd_kp[1] + radius), fill=color, width=2)

            if not correct:
                draw.line((prd_kp[0], prd_kp[1], trg_kp[0], trg_kp[1]), fill=color, width=1)

        pair_img.save(path)
`

Add below code (after keypoint prediction) in test.py.

`

        tmp_kps = Geometry.unnormalize_kps(prd_kps)
        for jdx, (sim, tim, spt, tpt, sbox, tbox, npts) in enumerate(zip(batch['src_img'], batch['trg_img'], batch['src_kps'], tmp_kps, batch['src_bbox'], batch['trg_bbox'], batch['n_pts'])):
            spt = spt[:, :npts].t()
            tpt = tpt[:, :npts].t()
            Visualizer.visualize_correspondences_bbox(sim, tim, spt, tpt, sbox, tbox, './vis/%d_%d.jpeg' % (idx, jdx))
        print()

`
