### ISSUE TITLE
Using new weights

### ISSUE THREAD

**Issue by Arseny-N** [juhongm999/chm#2]
Hello @juhongm999 !

Thank you for such great work. 

I am experiencing an issue with the new weights located on your google drive. 

If I try to use them with pytorch 1.3.1 I get the following error:
```
ValueError                                Traceback (most recent call last)
~/.anaconda3/envs/chm/lib/python3.7/tarfile.py in nti(s)
    186             s = nts(s, "ascii", "strict")
--> 187             n = int(s.strip() or "0", 8)
    188         except ValueError:

ValueError: invalid literal for int() with base 8: '_tensor_'
 ...
~/.anaconda3/envs/chm/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    597             if _is_zipfile(f):
    598                 # .zip is used for torch.jit.save and will throw an un-pickling error here
--> 599                 raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
    600             # if not a tarfile, reset file offset and proceed
    601             f.seek(0)

RuntimeError: pas_psi.pt is a zip archive (did you mean to use torch.jit.load()?)
```
The full error could be found [here](https://gist.github.com/Arseny-N/e89779d0e19ce46666f4b95ebcb492c0).

But if I use the 1.8.1 version of pytorch I get the following error. 

```
  Missing key(s) in state_dict: "learner.conv2ds.0.weight", "learner.conv2ds.1.weight", "learner.conv2ds.2.weight", "learner.chm6d.bias", "learner.chm6d.param". 
	  Unexpected key(s) in state_dict: "learner.conv2ds.0.0.weight", "learner.conv2ds.0.1.weight", "learner.conv2ds.0.2.weight", "learner.chm6d.0.bias", "learner.chm6d.0.param.0", "learner.chm6d.0.param.1", "learner.chm6d.0.param.2", "learner.chm6d.0.param.3". 
	  size mismatch for learner.chm4d.weight: copying a param with shape torch.Size([55]) from checkpoint, the shape in current model is torch.Size([1, 1, 5, 5, 5, 5]).

```

I believe this happens because the weights are for a slightly newer network, then the one currently in the repo. Is there any chance you could update the network in the repository ?

Thanks in advance, 
Arseny

**Comment by juhongm999** [comment]
Did you download pretrained model from the provided link [[Google drive](https://drive.google.com/drive/folders/1myRkb2ow6ltAWaAJtJsh23NVB6d4YFuo)] ?
In the public drive there is a directory named 'old' where we put the pretrained weights for the CHM.
Sorry for the confusion and let me know if you resolved the issue.

Please ignore new weights for the CHM and use the old ones.
The new ones are for private (testing) purpose.
We will update the link to the pretrained models appropriately

**Comment by Arseny-N** [comment]
Yes, thank you for clarifying!
I did find the correct model and eventually made it work.
