### ISSUE TITLE
Can't find 'test_pairs.csv' in pf-pascal datasets

### ISSUE THREAD

**Issue by aruba01** [juhongm999/chm#3]
when I run the `test.py` on pf-pascal dataset, it error with `FileNotFoundError: [Errno 2] No such file or directory: '/home/xx/chm/Datasets/PF-PASCAL/test_pairs.csv'`.
The pf-pascal dataset I used is downloaded from `https://www.di.ens.fr/willow/research/proposalflow/`.
The url of pf-pascal dataset in `download.py` cannot connected, `https://docs.google.com/uc?export=download?id=1OOwpGzJnTsFXYh-YffMQ9XKM_Kl_zdzg` return `400`.

**Comment by juhongm999** [comment]
Can you try this and see if it works?
`pip install gdown`
`gdown https://drive.google.com/uc?id=1OOwpGzJnTsFXYh-YffMQ9XKM_Kl_zdzg`

**Comment by aruba01** [comment]
It works, thank you!
The networks seems can only find matches between the images with same class of object, such as car, bird. I want to know that can the model apply to image matching task (only need correct matches, it doesn't matter that the correspondence point is keypoint or not)?

**Comment by juhongm999** [comment]
Do you mean something like image retrieval, finding top-k similar images given a query image ?

**Comment by aruba01** [comment]
Not image retrieval. I mean that given two similiar image (has been given by image retrieval or other approaches), the task is to find matches of points in two images which represent the same 3D point in world.
Like the following picture:
![image](https://user-images.githubusercontent.com/47864285/159160566-fa55c49d-28c3-4009-8b7a-a0e699cf1fc0.png)

**Comment by aruba01** [comment]
By a rough understanding of the paper and code, if I want to apply the network on image matching, it seems I should specify the points uesd in matching in advance? 
I find that the paper mentioned that top-300 matches generated by regular grid, dose it mean equal interval sampling in source image? (I think the process of acquire top-300 matches is similar to image matching)

**Comment by juhongm999** [comment]
By a rough understanding of the paper and code, if I want to apply the network on image matching, it seems I should specify the points uesd in matching in advance?

- Yes keypoints in either one of the images should be specified. You might want to refer paper like D2Net ([link](https://arxiv.org/abs/1905.03561)).

I find that the paper mentioned that top-300 matches generated by regular grid, dose it mean equal interval sampling in source image? (I think the process of acquire top-300 matches is similar to image matching)

- Yes keypoints are sampled uniformly.
