### ISSUE TITLE
Can't download dataset  'pfpascal' and 'spair'

### ISSUE THREAD

**Issue by OMEGA-Y** [juhongm999/chm#5]
Hi @juhongm999,
Thanks for your great work.

When I run the `train.py` on pfpascal and spair, respectively, it errors with `OSError: Not a gzipped file (b'<!')` and `tarfile.ReadError: not a gzip file`. I think the error occurs line 44 in `download.py`.

Could you check it?

the command I did : `python train.py --ktype psi --benchmark spair`

**Comment by juhongm999** [comment]
Sorry for late reply.
Somehow our code doesn't download datasets automatically with newer version of python packages.
Please refer to https://drive.google.com/drive/folders/1ew7Vm1tXKEukQZ22xVzAsPCeOJ50rPKr?usp=sharing for the datasets.
