### ISSUE TITLE
A question about test.csv of PF-WILLOW

### ISSUE THREAD

**Issue by senerit** [juhongm999/chm#6]
Hello! when I run the test.py on pf-willow dataset, it error with FileNotFoundError: [Errno 2] No such file or directory: '/home/xx/chm/Datasets/PF-WILLOW/test_pairs.csv'.
The PF-WILLOW dataset I used is downloaded from https://www.di.ens.fr/willow/research/proposalflow/.
Please help me ! Please!

**Comment by juhongm999** [comment]
Hello,

https://drive.google.com/drive/folders/1ew7Vm1tXKEukQZ22xVzAsPCeOJ50rPKr?usp=sharing

You will find PF-WILLOW dataset in the above google drive.
test_pairs.csv is inside the file as below.
![image](https://user-images.githubusercontent.com/41140817/186369508-e3a5193d-5558-4969-999c-f4cce171b507.png)

**Comment by senerit** [comment]
Thank you very much for your reply!



At 2022-08-24 16:27:52, "Juhong Min" ***@***.***> wrote:

Hello,

https://drive.google.com/drive/folders/1ew7Vm1tXKEukQZ22xVzAsPCeOJ50rPKr?usp=sharing

You will find PF-WILLOW dataset in the above google drive.
test_pairs.csv is inside the file as below.

**Comment by senerit** [comment]
Excuse me. I have one more question. It can work when I set  batch size=1. But when batch size is not equal 1 , procedure will report an error: Runtime Error: stack expects each tensor to be equal size, but got [3, 200, 300] at entry 0 and [3, 300, 225] at entry 1. How to solve this problem？ Please help me. Thank you.

**Comment by juhongm999** [comment]
The size of input images must be the same in order to make them into a tensor.
